services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: "50051"
      ORDER_SERVICE_HOST: order-service
      ORDER_SERVICE_PORT: "50052"
      JWT_SECRET: dev_secret
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    ports:
      - "50051:50051"
    environment:
      DATABASE_URL: postgresql+psycopg://finance:finance@db:5432/microservice_user
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: finance
      POSTGRES_DB: microservice_user
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
